version: 2.1
jobs:
  test:
    docker:
      - image: circleci/clojure:lein-2.9.1-node
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn package cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run: yarn install --immutable
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - run: ./script/test
workflows:
  test:
    jobs:
      - test
